openapi: '3.1.0'
info:
  title: SwiftServerTodos
  description: Create, read, delete, and list TODOs.
  version: 1.0.0
servers:
  - url: /api
    description: Invoke methods on this server.
tags:
  - name: TODOs
components:
  schemas:
    TODODetail:
      description: The details of a TODO.
      properties:
        id:
          description: A unique identifier of the TODO.
          type: string
          format: uuid
        contents:
          description: The contents of the TODO.
          type: string
      required:
        - id
        - contents
    PageOfTODOs:
      description: A single page of TODOs.
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/TODODetail'
      required:
        - items
    CreateTODORequest:
      description: The metadata required to create a TODO.
      properties:
        contents:
          description: The contents of the TODO.
          type: string
      required:
        - contents
