openapi: '3.1.0'
info:
  title: SwiftServerTodos
  description: Create, read, delete, and list TODOs.
  version: 1.0.0
servers:
  - url: /api
    description: Invoke methods on this server.
tags:
  - name: TODOs
components:
  schemas:
    TODODetail:
      description: The details of a TODO.
      properties:
        id:
          description: A unique identifier of the TODO.
          type: string
          format: uuid
        contents:
          description: The contents of the TODO.
          type: string
      required:
        - id
        - contents
